In [33]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score,confusion_matrix

# Reading the dataset

In [34]:
data=pd.read_csv(r"C:\Users\91908\Downloads\dataset_website.csv")
data.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [35]:
data.shape

(11055, 32)

In [36]:
data.drop("index",axis=1,inplace=True)

In [37]:
data.head()

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                          -1              1                   1   
1                           1              1                   1   
2                           1              0                   1   
3                           1              0                   1   
4                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  Favicon  \
0                 -1              -1                           -1        1   
1                  0               1                           -1        1   
2                 -1              -1                           -1        1   
3                 -1              -1                            1        1   
4                  1               1                           -1        1   

   ...  popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0  ...            1       1             -1         -1           -1         -1   
1  ...            1       1             -1         -1            0         -1   
2  ...            1       1              1         -1            1         -1   
3  ...            1       1             -1         -1            1         -1   
4  ...           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 31 columns]

# Handling null values

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   having_IPhaving_IP_Address   11055 non-null  int64
 1   URLURL_Length                11055 non-null  int64
 2   Shortining_Service           11055 non-null  int64
 3   having_At_Symbol             11055 non-null  int64
 4   double_slash_redirecting     11055 non-null  int64
 5   Prefix_Suffix                11055 non-null  int64
 6   having_Sub_Domain            11055 non-null  int64
 7   SSLfinal_State               11055 non-null  int64
 8   Domain_registeration_length  11055 non-null  int64
 9   Favicon                      11055 non-null  int64
 10  port                         11055 non-null  int64
 11  HTTPS_token                  11055 non-null  int64
 12  Request_URL                  11055 non-null  int64
 13  URL_of_Anchor                11055 non-null  i

In [39]:
data.isnull().any()

having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
Page_Rank                      False
G

# Splitting the data

In [40]:
x=data.iloc[:,0:30].values
y=data.iloc[:,-1].values
print(x,y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


# Training and testing

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

# Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [25]:
model.fit(x_train,y_train)

LogisticRegression()

In [55]:
pred_test_log=model.predict(x_test)
pred_test_log

array([-1,  1, -1, ...,  1, -1,  1], dtype=int64)

Evaluation metrics

In [73]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,r2_score,f1_score,precision_score,recall_score
print('test accuracy score: ',accuracy_score(y_test,pred_test_log))
print('test confusion matrix: ',confusion_matrix(y_test,pred_test_log))
print('test r2 score: ',r2_score(y_test,pred_test_log))
print('test f1 score: ',f1_score(y_test,pred_test_log))
print('test precision score: ',precision_score(y_test,pred_test_log))
print('test recall score: ',recall_score(y_test,pred_test_log))
print('test classification report: ',classification_report(y_test,pred_test_log))

test accuracy score:  0.9258365993367501
test confusion matrix:  [[1344  146]
 [ 100 1727]]
test r2 score:  0.7002523666258913
test f1 score:  0.9335135135135135
test precision score:  0.9220501868659904
test recall score:  0.9452654625068418
test classification report:                precision    recall  f1-score   support

          -1       0.93      0.90      0.92      1490
           1       0.92      0.95      0.93      1827

    accuracy                           0.93      3317
   macro avg       0.93      0.92      0.92      3317
weighted avg       0.93      0.93      0.93      3317



# Naive Bayes

In [19]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

In [57]:
pred_test_nb=nb.predict(x_test)
pred_test_nb

array([-1, -1, -1, ..., -1, -1, -1], dtype=int64)

In [74]:
print('test accuracy score: ',accuracy_score(y_test,pred_test_nb))
print('test confusion matrix: ',confusion_matrix(y_test,pred_test_nb))
print('test r2 score: ',r2_score(y_test,pred_test_nb))
print('test f1 score: ',f1_score(y_test,pred_test_nb))
print('test precision score: ',precision_score(y_test,pred_test_nb))
print('test recall score: ',recall_score(y_test,pred_test_nb))
print('test classification report: ',classification_report(y_test,pred_test_nb))

test accuracy score:  0.6261682242990654
test confusion matrix:  [[1487    3]
 [1237  590]]
test r2 score:  -0.5109230300158327
test f1 score:  0.487603305785124
test precision score:  0.9949409780775716
test recall score:  0.3229337712096333
test classification report:                precision    recall  f1-score   support

          -1       0.55      1.00      0.71      1490
           1       0.99      0.32      0.49      1827

    accuracy                           0.63      3317
   macro avg       0.77      0.66      0.60      3317
weighted avg       0.79      0.63      0.59      3317



# Decision Tree

In [59]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [60]:
pred_test_dt=dt.predict(x_test)
pred_test_dt

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [75]:
print('test accuracy score: ',accuracy_score(y_test,pred_test_dt))
print('test confusion matrix: ',confusion_matrix(y_test,pred_test_dt))
print('test r2 score: ',r2_score(y_test,pred_test_dt))
print('test f1 score: ',f1_score(y_test,pred_test_dt))
print('test precision score: ',precision_score(y_test,pred_test_dt))
print('test recall score: ',recall_score(y_test,pred_test_dt))
print('test classification report: ',classification_report(y_test,pred_test_dt))

test accuracy score:  0.9583961410913476
test confusion matrix:  [[1415   75]
 [  63 1764]]
test r2 score:  0.8318488885950122
test f1 score:  0.9623567921440261
test precision score:  0.9592169657422512
test recall score:  0.9655172413793104
test classification report:                precision    recall  f1-score   support

          -1       0.96      0.95      0.95      1490
           1       0.96      0.97      0.96      1827

    accuracy                           0.96      3317
   macro avg       0.96      0.96      0.96      3317
weighted avg       0.96      0.96      0.96      3317



# KNN

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [63]:
pred_test_knn=knn.predict(x_test)
pred_test_knn

array([-1,  1,  1, ...,  1, -1, -1], dtype=int64)

In [76]:
print('test accuracy score: ',accuracy_score(y_test,pred_test_knn))
print('test confusion matrix: ',confusion_matrix(y_test,pred_test_knn))
print('test r2 score: ',r2_score(y_test,pred_test_knn))
print('test f1 score: ',f1_score(y_test,pred_test_knn))
print('test precision score: ',precision_score(y_test,pred_test_knn))
print('test recall score: ',recall_score(y_test,pred_test_knn))
print('test classification report: ',classification_report(y_test,pred_test_knn))

test accuracy score:  0.9384986433524269
test confusion matrix:  [[1377  113]
 [  91 1736]]
test r2 score:  0.7514287918361049
test f1 score:  0.9445048966267682
test precision score:  0.9388858842617631
test recall score:  0.9501915708812261
test classification report:                precision    recall  f1-score   support

          -1       0.94      0.92      0.93      1490
           1       0.94      0.95      0.94      1827

    accuracy                           0.94      3317
   macro avg       0.94      0.94      0.94      3317
weighted avg       0.94      0.94      0.94      3317



# Random Forest

In [53]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [65]:
pred_test_rf=rf.predict(x_test)
pred_test_rf

array([-1,  1,  1, ...,  1,  1,  1], dtype=int64)

In [77]:
print('test accuracy score: ',accuracy_score(y_test,pred_test_rf))
print('test confusion matrix: ',confusion_matrix(y_test,pred_test_rf))
print('test r2 score: ',r2_score(y_test,pred_test_rf))
print('test f1 score: ',f1_score(y_test,pred_test_rf))
print('test precision score: ',precision_score(y_test,pred_test_rf))
print('test recall score: ',recall_score(y_test,pred_test_rf))
print('test classification report: ',classification_report(y_test,pred_test_rf))

test accuracy score:  0.967741935483871
test confusion matrix:  [[1424   66]
 [  41 1786]]
test r2 score:  0.869621964345408
test f1 score:  0.9709160097852677
test precision score:  0.9643628509719222
test recall score:  0.9775588396278051
test classification report:                precision    recall  f1-score   support

          -1       0.97      0.96      0.96      1490
           1       0.96      0.98      0.97      1827

    accuracy                           0.97      3317
   macro avg       0.97      0.97      0.97      3317
weighted avg       0.97      0.97      0.97      3317

