In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score,confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn import metrics 
import warnings
import math

# Reading the dataset

In [2]:
data= pd.read_csv(r"C:\Users\Anand\PycharmProjects\ibm\dataset_website.csv")
data.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [3]:
data.shape

(11055, 32)

In [4]:
data.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [5]:
data.tail()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
11050                -1                         1              1   
11051                -1                        -1             -1   
11052                 1                         1             -1   
11053                 1                         1             -1   
11054                 1                         1             -1   

       having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
11050                  1               1                           -1  ...   
11051                  1              -1                           -1  ...   
11052                  1              -1                           -1  ...   
11053                 -1              -1                            1  ...   
11054                 -1              -1                            1  ...   

       popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
11050           -1      -1              1          1           -1         -1   
11051           -1       1              1          1            1          1   
11052            1       1              1          1            1         -1   
11053           -1       1              1          1            1         -1   
11054            1       1             -1          1           -1         -1   

       Google_Index  Links_pointing_to_page  Statistical_report  Result  
11050             1                       1                   1       1  
11051             1                      -1                   1      -1  
11052             1                       0                   1      -1  
11053             1                       1                   1      -1  
11054            -1                       1                  -1      -1  

[5 rows x 32 columns]

In [6]:
data.shape

(11055, 32)

In [7]:
data.columns

Index(['index', 'having_IPhaving_IP_Address', 'URLURL_Length',
       'Shortining_Service', 'having_At_Symbol', 'double_slash_redirecting',
       'Prefix_Suffix', 'having_Sub_Domain', 'SSLfinal_State',
       'Domain_registeration_length', 'Favicon', 'port', 'HTTPS_token',
       'Request_URL', 'URL_of_Anchor', 'Links_in_tags', 'SFH',
       'Submitting_to_email', 'Abnormal_URL', 'Redirect', 'on_mouseover',
       'RightClick', 'popUpWidnow', 'Iframe', 'age_of_domain', 'DNSRecord',
       'web_traffic', 'Page_Rank', 'Google_Index', 'Links_pointing_to_page',
       'Statistical_report', 'Result'],
      dtype='object')

# Handling null values

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

In [9]:
data.nunique()

index                          11055
having_IPhaving_IP_Address         2
URLURL_Length                      3
Shortining_Service                 2
having_At_Symbol                   2
double_slash_redirecting           2
Prefix_Suffix                      2
having_Sub_Domain                  3
SSLfinal_State                     3
Domain_registeration_length        2
Favicon                            2
port                               2
HTTPS_token                        2
Request_URL                        2
URL_of_Anchor                      3
Links_in_tags                      3
SFH                                3
Submitting_to_email                2
Abnormal_URL                       2
Redirect                           2
on_mouseover                       2
RightClick                         2
popUpWidnow                        2
Iframe                             2
age_of_domain                      2
DNSRecord                          2
web_traffic                        3
P

In [10]:
data.isnull().any()

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

In [11]:
data.describe()


index  having_IPhaving_IP_Address  URLURL_Length  \
count  11055.000000                11055.000000   11055.000000   
mean    5528.000000                    0.313795      -0.633198   
std     3191.447947                    0.949534       0.766095   
min        1.000000                   -1.000000      -1.000000   
25%     2764.500000                   -1.000000      -1.000000   
50%     5528.000000                    1.000000      -1.000000   
75%     8291.500000                    1.000000      -1.000000   
max    11055.000000                    1.000000       1.000000   

       Shortining_Service  having_At_Symbol  double_slash_redirecting  \
count        11055.000000      11055.000000              11055.000000   
mean             0.738761          0.700588                  0.741474   
std              0.673998          0.713598                  0.671011   
min             -1.000000         -1.000000                 -1.000000   
25%              1.000000          1.000000                  1.000000   
50%              1.000000          1.000000                  1.000000   
75%              1.000000          1.000000                  1.000000   
max              1.000000          1.000000                  1.000000   

       Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
count   11055.000000       11055.000000    11055.000000   
mean       -0.734962           0.063953        0.250927   
std         0.678139           0.817518        0.911892   
min        -1.000000          -1.000000       -1.000000   
25%        -1.000000          -1.000000       -1.000000   
50%        -1.000000           0.000000        1.000000   
75%        -1.000000           1.000000        1.000000   
max         1.000000           1.000000        1.000000   

       Domain_registeration_length  ...   popUpWidnow        Iframe  \
count                 11055.000000  ...  11055.000000  11055.000000   
mean                     -0.336771  ...      0.613388      0.816915   
std                       0.941629  ...      0.789818      0.576784   
min                      -1.000000  ...     -1.000000     -1.000000   
25%                      -1.000000  ...      1.000000      1.000000   
50%                      -1.000000  ...      1.000000      1.000000   
75%                       1.000000  ...      1.000000      1.000000   
max                       1.000000  ...      1.000000      1.000000   

       age_of_domain     DNSRecord   web_traffic     Page_Rank  Google_Index  \
count   11055.000000  11055.000000  11055.000000  11055.000000  11055.000000   
mean        0.061239      0.377114      0.287291     -0.483673      0.721574   
std         0.998168      0.926209      0.827733      0.875289      0.692369   
min        -1.000000     -1.000000     -1.000000     -1.000000     -1.000000   
25%        -1.000000     -1.000000      0.000000     -1.000000      1.000000   
50%         1.000000      1.000000      1.000000     -1.000000      1.000000   
75%         1.000000      1.000000      1.000000      1.000000      1.000000   
max         1.000000      1.000000      1.000000      1.000000      1.000000   

       Links_pointing_to_page  Statistical_report        Result  
count            11055.000000        11055.000000  11055.000000  
mean                 0.344007            0.719584      0.113885  
std                  0.569944            0.694437      0.993539  
min                 -1.000000           -1.000000     -1.000000  
25%                  0.000000            1.000000     -1.000000  
50%                  0.000000            1.000000      1.000000  
75%                  1.000000            1.000000      1.000000  
max                  1.000000            1.000000      1.000000  

[8 rows x 32 columns]

# Splitting the data

In [12]:
A = data.drop(["Result"],axis =1)
B = data["Result"]

In [13]:
from sklearn.model_selection import train_test_split

A_train, A_test, B_train, B_test = train_test_split(A, B, test_size = 0.2, random_state = 42)
A_train.shape, B_train.shape, A_test.shape, B_test.shape

((8844, 31), (8844,), (2211, 31), (2211,))

In [14]:
x=data.iloc[:,1:31].values
y=data.iloc[:,-1].values
print(x,y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


# Training and testing

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [16]:
ML_Model = []
accuracy = []
f1_score = []
recall = []
precision = []

#function to call for storing the results
def storeResults(model, a,b,c,d):
  ML_Model.append(model)
  accuracy.append(round(a, 3))
  f1_score.append(round(b, 3))
  recall.append(round(c, 3))
  precision.append(round(d, 3))

# Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [18]:
model.fit(x_train,y_train)

LogisticRegression()

In [19]:
pred_test_log=model.predict(x_test)
pred_test_log

array([-1,  1, -1, ...,  1, -1,  1], dtype=int64)

In [20]:
y_train_model = model.predict(x_train)
y_test_model = model.predict(x_test)

In [21]:

accuracy_train = metrics.accuracy_score(y_train,y_train_model)
accuracy_test = metrics.accuracy_score(y_test,y_test_model)
print("Logistic Regression : Accuracy on training Data: {:.3f}".format(accuracy_train))
print("Logistic Regression : Accuracy on test Data: {:.3f}".format(accuracy_test))
print()

f1_score_train = metrics.f1_score(y_train,y_train_model)
f1_score_test = metrics.f1_score(y_test,y_test_model)
print("Logistic Regression : f1_score on training Data: {:.3f}".format(f1_score_train))
print("Logistic Regression : f1_score on test Data: {:.3f}".format(f1_score_test))
print()

recall_score_train = metrics.recall_score(y_train,y_train_model)
recall_score_test = metrics.recall_score(y_test,y_test_model)
print("Logistic Regression : Recall on training Data: {:.3f}".format(recall_score_train))
print("Logistic Regression : Recall on test Data: {:.3f}".format(recall_score_test))
print()

precision_score_train = metrics.precision_score(y_train,y_train_model)
precision_score_test = metrics.precision_score(y_test,y_test_model)
print("Logistic Regression : precision on training Data: {:.3f}".format(precision_score_train))
print("Logistic Regression : precision on test Data: {:.3f}".format(precision_score_test))


Logistic Regression : Accuracy on training Data: 0.928
Logistic Regression : Accuracy on test Data: 0.926

Logistic Regression : f1_score on training Data: 0.937
Logistic Regression : f1_score on test Data: 0.934

Logistic Regression : Recall on training Data: 0.946
Logistic Regression : Recall on test Data: 0.945

Logistic Regression : precision on training Data: 0.928
Logistic Regression : precision on test Data: 0.922


In [22]:
storeResults('Logistic Regression',accuracy_test,f1_score_test,
             recall_score_train,precision_score_train)

# Random Forest

In [51]:
from sklearn.ensemble import RandomForestClassifier
model_rf=RandomForestClassifier()

In [52]:
model_rf.fit(x_train,y_train)

RandomForestClassifier()

In [53]:
y_train_model = model_rf.predict(x_train)
y_test_model = model_rf.predict(x_test)

In [54]:
accuracy_train = metrics.accuracy_score(y_train,y_train_model)
accuracy_test = metrics.accuracy_score(y_test,y_test_model)
print("Logistic Regression : Accuracy on training Data: {:.3f}".format(accuracy_train))
print("Logistic Regression : Accuracy on test Data: {:.3f}".format(accuracy_test))
print()

f1_score_train = metrics.f1_score(y_train,y_train_model)
f1_score_test = metrics.f1_score(y_test,y_test_model)
print("Logistic Regression : f1_score on training Data: {:.3f}".format(f1_score_train))
print("Logistic Regression : f1_score on test Data: {:.3f}".format(f1_score_test))
print()

recall_score_train = metrics.recall_score(y_train,y_train_model)
recall_score_test = metrics.recall_score(y_test,y_test_model)
print("Logistic Regression : Recall on training Data: {:.3f}".format(recall_score_train))
print("Logistic Regression : Recall on test Data: {:.3f}".format(recall_score_test))
print()

precision_score_train = metrics.precision_score(y_train,y_train_model)
precision_score_test = metrics.precision_score(y_test,y_test_model)
print("Logistic Regression : precision on training Data: {:.3f}".format(precision_score_train))
print("Logistic Regression : precision on test Data: {:.3f}".format(precision_score_test))

Logistic Regression : Accuracy on training Data: 0.991
Logistic Regression : Accuracy on test Data: 0.967

Logistic Regression : f1_score on training Data: 0.992
Logistic Regression : f1_score on test Data: 0.970

Logistic Regression : Recall on training Data: 0.995
Logistic Regression : Recall on test Data: 0.980

Logistic Regression : precision on training Data: 0.989
Logistic Regression : precision on test Data: 0.960


In [55]:
storeResults('Random Forest',accuracy_test,f1_score_test,
             recall_score_train,precision_score_train)

# KNN

In [28]:
from sklearn.neighbors import KNeighborsClassifier
model= KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [30]:
pred_test_knn=model.predict(x_test)
pred_test_knn

array([-1,  1,  1, ...,  1, -1, -1], dtype=int64)

In [31]:
y_train_model = model.predict(x_train)
y_test_model = model.predict(x_test)

In [32]:
accuracy_train = metrics.accuracy_score(y_train,y_train_model)
accuracy_test = metrics.accuracy_score(y_test,y_test_model)
print("Logistic Regression : Accuracy on training Data: {:.3f}".format(accuracy_train))
print("Logistic Regression : Accuracy on test Data: {:.3f}".format(accuracy_test))
print()

f1_score_train = metrics.f1_score(y_train,y_train_model)
f1_score_test = metrics.f1_score(y_test,y_test_model)
print("Logistic Regression : f1_score on training Data: {:.3f}".format(f1_score_train))
print("Logistic Regression : f1_score on test Data: {:.3f}".format(f1_score_test))
print()

recall_score_train = metrics.recall_score(y_train,y_train_model)
recall_score_test = metrics.recall_score(y_test,y_test_model)
print("Logistic Regression : Recall on training Data: {:.3f}".format(recall_score_train))
print("Logistic Regression : Recall on test Data: {:.3f}".format(recall_score_test))
print()

precision_score_train = metrics.precision_score(y_train,y_train_model)
precision_score_test = metrics.precision_score(y_test,y_test_model)
print("Logistic Regression : precision on training Data: {:.3f}".format(precision_score_train))
print("Logistic Regression : precision on test Data: {:.3f}".format(precision_score_test))

Logistic Regression : Accuracy on training Data: 0.975
Logistic Regression : Accuracy on test Data: 0.938

Logistic Regression : f1_score on training Data: 0.978
Logistic Regression : f1_score on test Data: 0.945

Logistic Regression : Recall on training Data: 0.983
Logistic Regression : Recall on test Data: 0.950

Logistic Regression : precision on training Data: 0.973
Logistic Regression : precision on test Data: 0.939


In [33]:
storeResults('KNN',accuracy_test,f1_score_test,
             recall_score_train,precision_score_train)

# Decision Tree

In [34]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [35]:
pred_test_dt=model.predict(x_test)
pred_test_dt

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [36]:
y_train_model = model.predict(x_train)
y_test_model = model.predict(x_test)

In [37]:
accuracy_train = metrics.accuracy_score(y_train,y_train_model)
accuracy_test = metrics.accuracy_score(y_test,y_test_model)
print("Logistic Regression : Accuracy on training Data: {:.3f}".format(accuracy_train))
print("Logistic Regression : Accuracy on test Data: {:.3f}".format(accuracy_test))
print()

f1_score_train = metrics.f1_score(y_train,y_train_model)
f1_score_test = metrics.f1_score(y_test,y_test_model)
print("Logistic Regression : f1_score on training Data: {:.3f}".format(f1_score_train))
print("Logistic Regression : f1_score on test Data: {:.3f}".format(f1_score_test))
print()

recall_score_train = metrics.recall_score(y_train,y_train_model)
recall_score_test = metrics.recall_score(y_test,y_test_model)
print("Logistic Regression : Recall on training Data: {:.3f}".format(recall_score_train))
print("Logistic Regression : Recall on test Data: {:.3f}".format(recall_score_test))
print()

precision_score_train = metrics.precision_score(y_train,y_train_model)
precision_score_test = metrics.precision_score(y_test,y_test_model)
print("Logistic Regression : precision on training Data: {:.3f}".format(precision_score_train))
print("Logistic Regression : precision on test Data: {:.3f}".format(precision_score_test))

Logistic Regression : Accuracy on training Data: 0.991
Logistic Regression : Accuracy on test Data: 0.958

Logistic Regression : f1_score on training Data: 0.992
Logistic Regression : f1_score on test Data: 0.962

Logistic Regression : Recall on training Data: 0.991
Logistic Regression : Recall on test Data: 0.965

Logistic Regression : precision on training Data: 0.993
Logistic Regression : precision on test Data: 0.959


In [38]:
storeResults('Decision Tree',accuracy_test,f1_score_test,
             recall_score_train,precision_score_train)

# Naive Bayes

In [39]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [40]:
pred_test_nb=model.predict(x_test)
pred_test_nb

array([-1, -1, -1, ..., -1, -1, -1], dtype=int64)

In [41]:
y_train_model = model.predict(x_train)
y_test_model = model.predict(x_test)

In [42]:
accuracy_train = metrics.accuracy_score(y_train,y_train_model)
accuracy_test = metrics.accuracy_score(y_test,y_test_model)
print("Logistic Regression : Accuracy on training Data: {:.3f}".format(accuracy_train))
print("Logistic Regression : Accuracy on test Data: {:.3f}".format(accuracy_test))
print()

f1_score_train = metrics.f1_score(y_train,y_train_model)
f1_score_test = metrics.f1_score(y_test,y_test_model)
print("Logistic Regression : f1_score on training Data: {:.3f}".format(f1_score_train))
print("Logistic Regression : f1_score on test Data: {:.3f}".format(f1_score_test))
print()

recall_score_train = metrics.recall_score(y_train,y_train_model)
recall_score_test = metrics.recall_score(y_test,y_test_model)
print("Logistic Regression : Recall on training Data: {:.3f}".format(recall_score_train))
print("Logistic Regression : Recall on test Data: {:.3f}".format(recall_score_test))
print()

precision_score_train = metrics.precision_score(y_train,y_train_model)
precision_score_test = metrics.precision_score(y_test,y_test_model)
print("Logistic Regression : precision on training Data: {:.3f}".format(precision_score_train))
print("Logistic Regression : precision on test Data: {:.3f}".format(precision_score_test))

Logistic Regression : Accuracy on training Data: 0.602
Logistic Regression : Accuracy on test Data: 0.626

Logistic Regression : f1_score on training Data: 0.450
Logistic Regression : f1_score on test Data: 0.488

Logistic Regression : Recall on training Data: 0.290
Logistic Regression : Recall on test Data: 0.323

Logistic Regression : precision on training Data: 0.997
Logistic Regression : precision on test Data: 0.995


In [43]:
storeResults('Naive Bayes',accuracy_test,f1_score_test,
             recall_score_train,precision_score_train)

# Comparison

In [44]:
result = pd.DataFrame({ 'ML Model' : ML_Model,
                        'Accuracy' : accuracy,
                        'f1_score' : f1_score,
                        'Recall'   : recall,
                        'Precision': precision,
                      })

In [45]:
result 

ML Model  Accuracy  f1_score  Recall  Precision
0  Logistic Regression     0.926     0.934   0.946      0.928
1        Random Forest     0.967     0.971   0.995      0.990
2                  KNN     0.938     0.945   0.983      0.973
3        Decision Tree     0.958     0.962   0.991      0.993
4          Naive Bayes     0.626     0.488   0.290      0.997

In [48]:
ascending_result=result.sort_values(by=['Accuracy', 'Precision'],ascending=False).reset_index(drop=True)

In [49]:
ascending_result

ML Model  Accuracy  f1_score  Recall  Precision
0        Random Forest     0.967     0.971   0.995      0.990
1        Decision Tree     0.958     0.962   0.991      0.993
2                  KNN     0.938     0.945   0.983      0.973
3  Logistic Regression     0.926     0.934   0.946      0.928
4          Naive Bayes     0.626     0.488   0.290      0.997

# Saving the model

In [57]:
import pickle
pickle.dump(model_rf,open('Phishing_Websites.pkl','wb'))